/**
 * Generates `openapi/frontera-api.yaml` from Nest Swagger decorators.
 *
 * Usage: npm run openapi:generate
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { NestFactory } from '@nestjs/core';
import { dump } from 'js-yaml';
import { AppModule } from '../src/app.module';
import { buildOpenApiDocument } from '../src/openapi-document';

async function main(): Promise<void> {
  const app = await NestFactory.create(AppModule, { logger: false });
  await app.init();

  const document = buildOpenApiDocument(app);
  const outDir = resolve(__dirname, '../openapi');
  const outFile = resolve(outDir, 'frontera-api.yaml');

  mkdirSync(outDir, { recursive: true });

  const header = [
    '# Frontera Scheduling API — OpenAPI 3.0',
    '#',
    '# Generated by: npm run openapi:generate',
    '# Do not edit by hand — update controllers/DTOs and regenerate.',
    '#',
    '# Lovable: import this file and set servers.url to your API Gateway base URL.',
    '#',
    '',
  ].join('\n');

  writeFileSync(outFile, header + dump(document, { lineWidth: 120, noRefs: true }), 'utf8');
  await app.close();

  // eslint-disable-next-line no-console
  console.log(`Wrote ${outFile}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
